---
# Simple playbook to test Ansible connectivity
# Run: ansible-playbook ping.yml

- name: Test Connection to Servers
  hosts: app_server
  gather_facts: no

  tasks:
    - name: Ping the server
      ping:

    - name: Get server hostname
      command: hostname
      register: hostname_output

    - name: Display hostname
      debug:
        msg: "Connected to: {{ hostname_output.stdout }}"

    - name: Check Docker status
      command: docker --version
      register: docker_version
      become: yes

    - name: Display Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
